const D=GAME_DATA,T=THREE,$=s=>document.querySelector(s),wait=ms=>new Promise(r=>setTimeout(r,ms));
const ui={intro:$('#intro'),loading:$('#loading'),progress:$('#progress'),header:$('#header'),steps:$('#steps'),enemy:$('#enemy'),player:$('#player'),command:$('#command'),skills:$('#skills'),info:$('#info'),turn:$('#turn'),prompt:$('#prompt'),msg:$('#message'),ma:$('#ma'),mm:$('#mm'),md:$('#md'),enc:$('#encounter'),evo:$('#evolution'),ending:$('#ending'),guide:$('#guide')};
const scene=new T.Scene();scene.background=new T.Color(0x18343e);scene.fog=new T.FogExp2(0x18343e,.032);const camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,7.3,12);camera.lookAt(0,1,0);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;$('#stage').appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0xd8fbff,0x17282d,2.05));const key=new T.DirectionalLight(0xf0fdff,2.8);key.position.set(-5,10,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const red=new T.PointLight(0xff766c,18,20);red.position.set(5,4,-2);scene.add(red);const floor=new T.Mesh(new T.CircleGeometry(13,64),new T.MeshStandardMaterial({color:0x294a52,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);for(const r of[4,8,12]){const x=new T.Mesh(new T.RingGeometry(r-.025,r+.025,80),new T.MeshBasicMaterial({color:0x8debf3,transparent:true,opacity:.24}));x.rotation.x=-Math.PI/2;x.position.y=.02;scene.add(x)}
const roots={player:new T.Group(),enemy:new T.Group()};roots.player.position.set(-4,0,1.7);roots.enemy.position.set(4,0,-1.2);scene.add(roots.player,roots.enemy);const vfx=new MoonVFX(scene,roots);let mixers=[],mode='loading',encounter=0,turn=1,lineage=['moon'],bloodline=null,usage={},P,E,busy=false;
const statNames=['hp','atk','arc','def','res','spd'],enemyPools={1:['moss','thunder','fin'],2:['lynx','frost','storm'],3:['iron','flare','mist'],4:['boss','iron','flare','mist']};
const shuffled=a=>[...a].sort(()=>Math.random()-.5);
function fighter(id,side,old,levelOverride){const source=D.creatures[id],level=levelOverride??source.level,c=level===source.level?source:{...source,level},scale=level<source.level?Math.pow(.84,source.level-level):1,stats=Object.fromEntries(statNames.map((n,i)=>[n,Math.round(source.stats[i]*scale)])),fixed=[...c.skillIds],ids=side==='player'&&bloodline&&!fixed.includes(bloodline)?[...fixed.slice(0,3),bloodline]:fixed.slice(0,4);return{c,side,stats,maxHp:stats.hp,hp:stats.hp,shield:0,skills:ids.map(id=>({...D.skills[id],left:D.skills[id].pp})),states:[],flags:{},dead:false}}
function elmod(a,b){if(a==='neutral'||b==='neutral')return 1;if(D.strong[a]===b)return 1.35;if(D.strong[b]===a)return .75;return 1}
function stat(f,n){let v=f.stats[n];for(const s of f.states)if(s.stat===n)v*=1+(s.amount||0);if(n==='spd'&&f.states.some(s=>s.type==='slow'))v*=.65;if(f.c.passive[0]==='phase'&&f.hp<=f.maxHp/2&&(n==='spd'||n==='atk'))v*=1.28;return v}
function stateText(f){return f.states.map(s=>`<span>${({burn:'灼燒',slow:'緩速',accuracy:'失準',def:'破甲',atk:'力量↑',arc:'靈能↑'})[s.type||s.stat]||s.type} ${s.turns}</span>`).join('')}
function refresh(){for(const[f,prefix]of[[P,'p'],[E,'e']]){if(!f)continue;const c=f.c,elem=D.elements[c.element];$('#'+prefix+'n').textContent=c.name;$('#'+prefix+'l').textContent=`Lv.${c.level}`;$('#'+prefix+'e').textContent=elem[0];$('#'+prefix+'e').style.color=elem[1];$('#'+prefix+'h').style.width=`${Math.max(0,f.hp/f.maxHp*100)}%`;$('#'+prefix+'s').style.width=`${Math.min(100,f.shield/f.maxHp*100)}%`;$('#'+prefix+'ht').textContent=`${Math.ceil(Math.max(0,f.hp))} / ${f.maxHp}`;$('#'+prefix+'p').innerHTML=`<b>${c.passive[1]}</b> · ${c.passive[2]}`;$('#'+prefix+'st').innerHTML=stateText(f)}ui.steps.innerHTML=D.encounters.map((_,i)=>`<i class="${i<encounter?'done':i===encounter?'now':''}"></i>`).join('')}
// Pages 以 gzip 傳輸，Content-Length 是壓縮後大小，所以總量改讀 GLB 檔頭（第 8–11 位元組）記錄的檔案長度。
async function fetchGlb(url,onProgress){const res=await fetch(url);if(!res.ok)throw new Error(`${url} ${res.status}`);if(!res.body)return res.arrayBuffer();const reader=res.body.getReader(),chunks=[];let loaded=0,total=0;for(;;){const{done,value}=await reader.read();if(done)break;chunks.push(value);loaded+=value.byteLength;if(!total&&loaded>=12){const head=new Uint8Array(12);let n=0;for(const c of chunks){const k=Math.min(c.byteLength,12-n);head.set(c.subarray(0,k),n);n+=k;if(n===12)break}total=new DataView(head.buffer).getUint32(8,true)}onProgress?.(loaded,total)}const data=new Uint8Array(loaded);let at=0;for(const c of chunks){data.set(c,at);at+=c.byteLength}return data.buffer}
function showProgress(loaded,total){if(!total)return;const text=`${Math.min(100,Math.floor(loaded/total*100))}%`;if(ui.progress.textContent!==text)ui.progress.textContent=text}
async function makeModel(c,side,onProgress){const data=await fetchGlb(`assets/models/${c.id}.glb`,onProgress);return new Promise((resolve,reject)=>new GLTFLoader().parse(data,'assets/models/',g=>{const wrap=new T.Group(),model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false}});const box=new T.Box3().setFromObject(model);model.position.y-=box.min.y;wrap.add(model);wrap.scale.setScalar(c.visual.scale*(side==='enemy'?.95:1));wrap.rotation.y=side==='player'?Math.PI/2:-Math.PI/2;const mixer=new T.AnimationMixer(model),acts={};g.animations.forEach(a=>acts[a.name]=mixer.clipAction(a));acts.idle?.play();mixers.push(mixer);wrap.userData={mixer,acts};resolve(wrap)},reject))}
async function showModels(onProgress){mixers=[];for(const side of['player','enemy']){const root=roots[side];while(root.children.length)root.remove(root.children[0]);const f=side==='player'?P:E;if(!f)continue;root.add(await makeModel(f.c,side,onProgress))}}
function playAnim(f,name){const m=roots[f.side].children[0]?.userData;if(!m)return;Object.values(m.acts).forEach(a=>a.stop());const a=m.acts[name]||m.acts.attack;if(a){a.reset();a.setLoop(name==='idle'?T.LoopRepeat:T.LoopOnce,1);a.clampWhenFinished=true;a.play();if(name!=='idle')setTimeout(()=>{Object.values(m.acts).forEach(x=>x.stop());m.acts.idle?.reset().play()},700)}}
async function say(actor,main,detail='',ms=850){ui.ma.textContent=actor;ui.mm.textContent=main;ui.md.textContent=detail;ui.msg.classList.remove('hidden');await wait(ms);ui.msg.classList.add('hidden')}
function float(f,text,kind=''){const d=document.createElement('div');d.className=`damage ${f.side==='player'?'left':'right'} ${kind}`;d.textContent=text;$('#float').appendChild(d);setTimeout(()=>d.remove(),1000)}
function renderSkills(){ui.skills.innerHTML='';P.skills.forEach((s,i)=>{const mod=elmod(s.element,E.c.element),b=document.createElement('button');b.className='skill';b.disabled=s.left<=0;b.innerHTML=`<em>${s.left}/${s.pp}</em><b>${i+1}. ${s.name}</b><small class="${mod>1?'good':mod<1?'bad':''}">${D.elements[s.element][0]} · ${s.cat==='status'?'變化':s.power+' 威力'}${mod>1?' · 有效':mod<1?' · 抵抗':''}</small>`;b.onmouseenter=()=>ui.info.textContent=s.desc;b.onclick=()=>choose(i);ui.skills.appendChild(b)});ui.turn.textContent=`TURN ${String(turn).padStart(2,'0')}`;ui.prompt.textContent=`選擇${P.c.name}的行動`}
function pickAI(){const usable=E.skills.filter(s=>s.left>0);let options=usable;if(E.hp/E.maxHp>.72)options=options.filter(s=>s.effect?.type!=='heal');if(E.shield>0)options=options.filter(s=>s.effect?.type!=='shield');return(options.length?options:usable)[Math.floor(Math.random()*(options.length||1))]}
async function choose(i){if(mode!=='battle'||busy)return;const ps=P.skills[i];if(!ps||ps.left<=0)return;busy=true;ui.command.classList.add('hidden');usage[ps.id]=(usage[ps.id]||0)+1;const es=pickAI(),order=[[P,ps],[E,es]].sort((a,b)=>(b[1].priority-a[1].priority)||(stat(b[0],'spd')-stat(a[0],'spd')));for(const[f,s]of order){if(f.dead)continue;await act(f,f===P?E:P,s);if((f===P?E:P).dead)break}if(!P.dead&&!E.dead){await endTurn(P);await endTurn(E)}refresh();if(P.dead)return finish(false);if(E.dead)return victory();turn++;renderSkills();ui.command.classList.remove('hidden');busy=false}
async function act(a,d,s){s.left--;playAnim(a,s.cat==='status'?'idle':'attack');const cast=vfx.cast(a,d,s);await say(a.c.name,s.name,s.desc,450);const acc=a.states.filter(x=>x.stat==='accuracy').reduce((m,x)=>m*(1-x.amount),1);if(Math.random()>s.accuracy*acc){await cast;await say('','攻擊落空','月塵改變了命運。',500);return}await cast;if(s.cat==='status'){applyEffect(a,d,s.effect);refresh();return}let atk=stat(a,s.cat==='physical'?'atk':'arc'),def=stat(d,s.cat==='physical'?'def':'res'),mod=elmod(s.element,d.c.element),crit=Math.random()<.08;if(a.c.passive[0]==='flare'&&!a.flags.flare){crit=true;a.flags.flare=true}let dmg=s.power*(atk/def)*(1+a.c.level*.04)*mod*(.92+Math.random()*.08)*(crit?1.5:1)*.55;if(a.c.passive[0]==='chargefur'&&a.flags.charged){dmg*=1.18;a.flags.charged=false}if(a.c.passive[0]==='huntburn'&&d.states.some(x=>x.type==='burn'))dmg*=1.25;if(a.c.passive[0]==='huntcold'&&d.states.some(x=>x.type==='slow'))dmg*=1.25;if(d.c.passive[0]==='ironroot'&&d.hp>d.maxHp/2)dmg*=.88;damage(d,Math.round(dmg));if(s.effect?.type&&Math.random()<(s.effect.chance??1))applyEffect(a,d,s.effect);if(s.effect?.recoil||s.recoil)damage(a,Math.round(dmg*(s.recoil||s.effect.recoil)));await wait(250);if(mod!==1||crit)await say('',`${crit?'暴擊！ ':''}${mod>1?'效果絕佳！':mod<1?'效果不佳…':''}`,`${Math.round(dmg)} 傷害`,450)}
function damage(f,n){let rest=n;if(f.shield){const used=Math.min(rest,f.shield);f.shield-=used;rest-=used}f.hp=Math.max(0,f.hp-rest);float(f,`-${n}`);if(f.c.passive[0]==='chargefur')f.flags.charged=true;if(f.c.passive[0]==='first'&&!f.flags.first&&f.hp/f.maxHp<.3){f.flags.first=true;f.shield+=f.maxHp*.25}f.dead=f.hp<=0;refresh();roots[f.side].position.x+=(f.side==='player'?-1:1)*.18;setTimeout(()=>roots[f.side].position.x=f.side==='player'?-4:4,160)}
function applyEffect(a,d,e){if(!e?.type)return;if(e.type==='shield'){a.shield=Math.max(a.shield,a.maxHp*e.ratio);return}if(e.type==='heal'){const n=Math.round(a.maxHp*e.ratio);a.hp=Math.min(a.maxHp,a.hp+n);float(a,`+${n}`,'heal');return}const self=['atk','arc'].includes(e.type),target=self?a:d;target.states=target.states.filter(x=>(x.type||x.stat)!==e.type);const amount=self?e.amount:e.type==='accuracy'?e.amount:-e.amount;target.states.push({type:['slow','burn'].includes(e.type)?e.type:null,stat:!['slow','burn'].includes(e.type)?e.type:null,amount,turns:e.turns})}
async function endTurn(f){const burn=f.states.find(s=>s.type==='burn');if(burn){const n=Math.round(f.maxHp*.06);damage(f,n);await say(f.c.name,'灼燒侵蝕',`${n} 傷害`,350)}if(f.c.passive[0]==='regen'&&!f.dead){const n=Math.round(f.maxHp*.03);f.hp=Math.min(f.maxHp,f.hp+n);float(f,`+${n}`,'heal')}for(const s of f.states)s.turns--;f.states=f.states.filter(s=>s.turns>0);f.dead=f.hp<=0}
async function victory(){mode='transition';await say('VICTORY',`擊敗 ${E.c.name}`,`${P.c.name}獲得進化資格`,1100);if(encounter===3)return finish(true);bloodline=Object.entries(usage).sort((a,b)=>b[1]-a[1])[0]?.[0]||P.skills[0].id;const old=P;encounter++;evolution(old)}
function evolution(old){mode='evolution';ui.evo.classList.remove('hidden');$('#old').textContent=`${old.c.name} 的血脈正在重組`;$('#new').textContent='選擇新的形態';$('#ne').textContent='';$('#desc').textContent='月蝕隨機揭示了三條進化路線。';$('#stats').innerHTML='';$('#kit').innerHTML='';$('#continue').classList.add('hidden');const choices=shuffled(D.pools[old.c.level+1]).slice(0,3),host=$('#evolution-options');host.innerHTML='';for(const id of choices){const c=D.creatures[id],el=D.elements[c.element],b=document.createElement('button');b.className='option';b.innerHTML=`<small>LV.${c.level} · ${c.role}</small><i style="color:${el[1]}">${el[0]}</i><b>${c.name}</b><span>${c.desc}<br>${c.passive[1]}：${c.passive[2]}</span>`;b.onclick=()=>selectEvolution(id,b);host.appendChild(b)}}
async function selectEvolution(id,button){if($('#continue').classList.contains('hidden')===false)return;document.querySelectorAll('#evolution-options .option').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');const old=P;P=fighter(id,'player',old);lineage.push(id);const n=P.c;$('#new').textContent=n.name;$('#ne').textContent=D.elements[n.element][0]+'元素';$('#desc').textContent=n.desc;$('#stats').innerHTML=statNames.map((x,i)=>`<span>${x.toUpperCase()} <b>${n.stats[i]}</b></span>`).join('');$('#kit').innerHTML=P.skills.map(s=>`<span class="${s.id===bloodline?'blood':''}">${s.name}${s.id===bloodline?' · 血脈技':''}</span>`).join('');$('#continue').classList.remove('hidden');await showModels();refresh()}
function showEncounter(){mode='encounter';E=null;$('#vp').textContent=P.c.name;$('#vpl').textContent=`Lv.${P.c.level}`;$('#hint').textContent='先選擇一名同級對手';$('#fight').classList.add('hidden');const choices=shuffled(enemyPools[P.c.level]).slice(0,3),host=$('#enemy-options');host.innerHTML='';for(const id of choices){const c=D.creatures[id],el=D.elements[c.element],b=document.createElement('button');b.className='option';b.innerHTML=`<small>LV.${P.c.level} · ${c.role}</small><i style="color:${el[1]}">${el[0]}</i><b>${c.name}</b><span>${c.passive[1]}：${c.passive[2]}</span>`;b.onclick=()=>{document.querySelectorAll('#enemy-options .option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');E=fighter(id,'enemy',null,P.c.level);$('#hint').textContent=c.desc;$('#fight').classList.remove('hidden');refresh()};host.appendChild(b)}ui.enc.classList.remove('hidden');ui.evo.classList.add('hidden');refresh()}
async function startBattle(){if(!E)return;mode='loading';ui.enc.classList.add('hidden');ui.player.classList.remove('hidden');ui.enemy.classList.remove('hidden');await showModels();turn=1;busy=false;if(P.c.passive[0]==='mist')E.states.push({stat:'accuracy',amount:.2,turns:2});refresh();await say('BATTLE START',`${P.c.name} VS ${E.c.name}`,`同級對戰：Lv.${E.c.level}`,900);mode='battle';renderSkills();ui.command.classList.remove('hidden')}
function finish(win){mode='ending';ui.command.classList.add('hidden');ui.player.classList.add('hidden');ui.enemy.classList.add('hidden');$('#over').textContent=win?'TRIAL COMPLETE':'THE ECLIPSE CLAIMS YOU';$('#end-title').textContent=win?'月光重返遺跡':'進化在此中止';$('#end-body').textContent=win?'你擊敗了蝕日暴君，走完本次進化鏈。':`你在 Lv.${P.c.level} 敗給了 ${E.c.name}。`;$('#lineage').innerHTML=lineage.map((id,i)=>`${i?'<i>→</i>':''}<span>${D.creatures[id].name}</span>`).join('');ui.ending.classList.remove('hidden')}
async function boot(){P=fighter('moon','player');await showModels(showProgress);ui.loading.classList.add('off');setTimeout(()=>ui.loading.classList.add('hidden'),500);mode='menu'}
function begin(){ui.intro.classList.add('hidden');ui.header.classList.remove('hidden');showEncounter()}$('#start').onclick=begin;$('#fight').onclick=startBattle;$('#continue').onclick=showEncounter;$('#restart').onclick=()=>location.reload();$('#help').onclick=()=>ui.guide.classList.remove('hidden');$('#close').onclick=()=>ui.guide.classList.add('hidden');addEventListener('keydown',e=>{if(e.code==='Enter'&&mode==='menu')begin();else if(e.code==='Enter'&&mode==='encounter')startBattle();else if(e.code==='Enter'&&mode==='evolution')showEncounter();else if(e.code==='KeyR'&&mode==='ending')location.reload();else if(mode==='battle'&&/^Digit[1-4]$/.test(e.code))choose(+e.code.at(-1)-1)});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});let last=performance.now();function loop(t){const dt=Math.min((t-last)/1000,.05);last=t;mixers.forEach(m=>m.update(dt));vfx.update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);boot().catch(e=>{console.error(e);ui.loading.textContent='模型載入失敗，請用本機伺服器啟動。'});
