name: Deploy knight_counter_demo

on:
  push:
    branches: [master]
    paths:
      - "knight_counter_demo/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_reusable-flutter-deploy.yaml
    with:
      project_dir: knight_counter_demo
