name: Deploy flutter_tetris

on:
  push:
    branches: [master]
    paths:
      - "flutter_tetris/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_reusable-flutter-deploy.yaml
    with:
      project_dir: flutter_tetris
